version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '4567-4597:4567-4597'
      - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack/root:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  terraform:
    image: hashicorp/terraform:0.11.14
    working_dir: /tmp/src
    volumes:
      - './:/tmp/src'
